[project]
name = "proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "stanza",
    "python-docx",
    "yt-dlp>=2026.3.17",
    "pandas>=3.0.2",
]

[dependency-groups]
dev = ["pytest"]

[tool.pytest.ini_options]
pythonpath = ["work"]
